---
- name: "initialize function"
  include_tasks: "includes/init.yaml"

- name: "Include bgp address-family tasks"
  include_role:
    name: "{{ ansible_network_provider }}"
    tasks_from: "bgp/address_family.yaml"
    defaults_from: "bgp/address_family.yaml"
