---
- name: set role supported functions
  set_fact:
    bgp_functions:
      - address_family
      - neighbor
      - network
      - process
      - noop

- name: validate the requested function is supported
  fail:
    msg: "invalid function specified, expected one of {{ bgp_functions }}, got {{ function }}"
  when: function | default('noop') not in bgp_functions

- name: "include function specific tasks and run"
  include_tasks: "{{ function  | default('noop') }}.yaml"

