---
- name: "initialize function"
  include_tasks: "includes/init.yaml"

- name: "Include bgp network tasks"
  include_role:
    name: "{{ ansible_network_provider }}"
    tasks_from: "bgp/network.yaml"
    defaults_from: "bgp/network.yaml"
